# Generated by Django 2.0.1 on 2018-06-26 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=120)),
                ('currency', models.CharField(max_length=3)),
                ('source', models.CharField(max_length=120)),
                ('captured', models.CharField(blank=True, max_length=120, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('refunded', models.BooleanField(default=False)),
                ('amount_refunded', models.IntegerField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, null=True)),
                ('outcome_type', models.CharField(blank=True, max_length=120, null=True)),
                ('seller_message', models.CharField(blank=True, max_length=120, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=120, null=True)),
                ('order_id', models.CharField(blank=True, max_length=120, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=120, null=True)),
                ('failure_message', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billings.BillingProfile')),
            ],
        ),
    ]
